version: "3"
services:
  db_postgres:
    build: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    expose:
      - 5432

  # # APP*****************************************
  ticket-log:
    
    build: .\ticket-log
    depends_on:
      - db_postgres
    links:
      - db_postgres
    expose:
      - 8400
    ports:
      - 8400:8400

  ticket-log-view:
    build: ticket-log-view
    expose:
      - 4200
    ports:
      - 4200:4200
    restart: unless-stopped
  
      
volumes:
  postgres-data:
  